In [ ]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
df=pd.read_csv("spammails.csv")
df.head()

Category                                           Masseges
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df['Category'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [ ]:
df.shape

(5572, 2)

In [ ]:
df.columns

Index(['Category', 'Masseges'], dtype='object')

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
print(df.shape)

(5169, 2)


In [ ]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
print(df.isnull().sum())

Category    0
Masseges    0
dtype: int64


In [ ]:
def check(text):
    x=[ch for ch in text if ch not in string.punctuation]
    x=''.join(x)
    cleandata=[word for word in x.split() if word.lower() not in stopwords.words('english')]
    return cleandata
df['Masseges'].head().apply(check)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: Masseges, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
msg=CountVectorizer(analyzer=check).fit_transform(df['Masseges'])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(msg,df['Category'],test_size=0.2,random_state=0)
print(msg.shape)

(5169, 11304)


In [ ]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB().fit(x_train,y_train)

In [ ]:
print(classifier.predict(x_train))

[0 0 0 ... 0 0 0]


In [ ]:
print(y_train.values)

[0 0 0 ... 0 0 0]


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
pred=classifier.predict(x_train)
cm=confusion_matrix
print(classification_report(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3631
           1       0.98      0.98      0.98       504

    accuracy                           1.00      4135
   macro avg       0.99      0.99      0.99      4135
weighted avg       1.00      1.00      1.00      4135



In [ ]:
print("Confusion Matrix is \n",cm(y_train,pred))

Confusion Matrix is 
 [[3623    8]
 [  11  493]]


In [ ]:
print("Accuracy is \n",accuracy_score(y_train,pred))

Accuracy is 
 0.9954050785973397


In [ ]:
print(classifier.predict(x_test))
print(y_test.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


Result

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
pred=classifier.predict(x_test)
cm=confusion_matrix
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.99      0.96      0.97       885
           1       0.80      0.93      0.86       149

    accuracy                           0.96      1034
   macro avg       0.89      0.94      0.92      1034
weighted avg       0.96      0.96      0.96      1034



In [ ]:
print("Confusion Matrix is \n",cm(y_test,pred))

Confusion Matrix is 
 [[850  35]
 [ 11 138]]


In [ ]:
print("Accuracy is \n",accuracy_score(y_test,pred))

Accuracy is 
 0.9555125725338491
